name: CI-Pipeline

# Controls when the workflow will run, when comment is created
on:
  issue_comment:
    types:
      - created

jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci-v2.yml@9e4b3b6074bf192eb73a03f97ea13db590b1c431
    secrets: inherit
    with:
      craSCCv2: true
      craTarget: "examples/default"
      craRuleIgnoreFile: "cra-tf-validate-ignore-rules.json"
