name: Release-Pipeline

on:
  workflow_run:
    workflows: [CI-Pipeline]
    branches: [main]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-terraform-release-pipeline:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: terraform-ibm-modules/common-dev-assets/.github/workflows/release.yml@main
    secrets: inherit
